import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className='h-screen' lang="en">
      <body className={inter.className}>
        <div className='mx-auto max-w-2xl px-6'>
          <header>
            <div className='text-center bg-slate-700 p-8 w-full mb-6 mt-5 md:mt-24 rounded-md'>
              <Link href="/">
                <h1 className="text-3xl text-white font-semibold">My Awesome Blog</h1>
              </Link>
              <p className='text-slate-300'>Welcome to my tech blog</p>
            </div>
          </header>
          {children}
          <footer>
            <div className='border-t border-slate-400 mt-6 py-6 text-center text-slate-400'>
              <h3>Powered by Next.js</h3>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
